validate:
  user:
    email:
      length:
        max: 255
      regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    name:
      length:
        max: 50
    password:
      length:
        min: 6
page_30: 30
gravatar_size: 80
